# Generated by Django 4.2.16 on 2024-11-18 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_brand', models.CharField(max_length=200)),
                ('product_price', models.FloatField(max_length=10)),
                ('product_old_price', models.FloatField(max_length=10)),
                ('product_discount', models.FloatField(max_length=10)),
                ('product_size', models.CharField(max_length=20)),
                ('product_description', models.CharField(max_length=200)),
                ('product_quantity', models.IntegerField(default=1)),
                ('product_availability', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('product_img_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_img', models.CharField(max_length=100)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productdetail', to='demoproject.productdetail')),
            ],
        ),
    ]
