# Generated by Django 4.2.16 on 2024-11-20 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoproject', '0002_productdetail_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddToCart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_img_name', models.CharField(default='', max_length=200)),
                ('product_brand', models.CharField(max_length=200)),
                ('product_description', models.CharField(max_length=200)),
                ('product_quantity', models.IntegerField(default=1)),
                ('product_size', models.CharField(max_length=20)),
                ('product_price', models.FloatField(max_length=10)),
                ('product_total_price', models.FloatField(max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='demoproject.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productdetails', to='demoproject.productdetail')),
                ('product_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productimage', to='demoproject.productimage')),
            ],
        ),
    ]
