# Generated by Django 4.2.16 on 2024-11-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoproject', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='forgot_password_token',
            field=models.CharField(default='', max_length=200),
        ),
    ]
